import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
interface ISuccessResult {}

const Dash: NextPage = () => {
  const router = useRouter();

  const [human, setHuman] = useState(false);

  const onSuccess = (result: ISuccessResult) => {
    setHuman(true);
    console.log(result);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Dutch</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
        {/* <script src="https://cdn.jsdelivr.net/npm/party-js@latest/bundle/party.min.js"></script> */}
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a className={styles.card} onClick={() => router.push("/trips")}>
            <h2>🚌 See Your Expenses &rarr;</h2>
            <p>Explore current and past expenses you and your frens have shared</p>
          </a>

          <a className={styles.card} onClick={() => router.push("/createTrip")}>
            <h2>✨ Create an Expense &rarr;</h2>
            <p>Venture forth with your frens on a new adventure</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Dash;
